name: Run Accessibility Tests on GitHub

permissions:
  contents: read

on:
  workflow_dispatch:
  workflow_call:
  repository_dispatch:
    types: [run-accessibility-tests]

  schedule:
    - cron: "0 8 * * *"

jobs:
  build:
    name: Run Accessibility Tests
    runs-on: ubuntu-latest

    env:
      MESSAGE_QUEUE_HOST: ${{ secrets.MESSAGE_QUEUE_HOST }}
      EVENT_QUEUE_ADDRESS: ${{ secrets.EVENT_QUEUE_ADDRESS }}
      MESSAGE_QUEUE_USER: ${{ secrets.MESSAGE_QUEUE_USER }}
      FCP_AHWR_EVENT_QUEUE_SA_KEY: ${{ secrets.FCP_AHWR_EVENT_QUEUE_SA_KEY }}
      AADAR_AUTHORITY_URL: ${{ secrets.AADAR_AUTHORITY_URL }}
      AADAR_CLIENT_SECRET: ${{ secrets.AADAR_CLIENT_SECRET }}
      AADAR_CLIENT_ID: ${{ secrets.AADAR_CLIENT_ID }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Run test script
        run: ./scripts/github_run_tests.sh accessibility

      - name: Upload Allure Report
        if: always()
        uses: actions/upload-artifact@v7
        with:
          name: allure-report
          path: allure-report/

      - name: Upload Logs
        if: failure()
        uses: actions/upload-artifact@v7
        with:
          name: logs
          path: logs/

      - name: Upload Screenshots
        if: failure()
        uses: actions/upload-artifact@v7
        with:
          name: screenshots
          path: screenshots/

      - name: Upload accessibility report
        if: always()
        uses: actions/upload-artifact@v7
        with:
          name: accessibility-report
          path: accessibility-report/
